# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 78cfb19c-00ec-4df6-9c13-00a6aa134000;curl;no-all-load,no-import;Release:curl,Debug:curl-d
# Disable with : `mulle-sourcetree mark curl no-link`
# Disable for this platform: `mulle-sourcetree mark curl no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark curl no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "Release:curl")
else()
   if( NOT CURL_LIBRARY)
      if( "${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
         find_library( CURL_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}curl-d${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}curl-d${CMAKE_STATIC_LIBRARY_SUFFIX}
            curl-d
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT CURL_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( CURL_LIBRARY NAMES
               ${CMAKE_STATIC_LIBRARY_PREFIX}curl-d${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}curl-d${CMAKE_STATIC_LIBRARY_SUFFIX}
               curl-d
            )
         endif()
      endif()
      if( NOT CURL_LIBRARY)
         find_library( CURL_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}curl${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}curl${CMAKE_STATIC_LIBRARY_SUFFIX}
            curl
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT CURL_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( CURL_LIBRARY NAMES
               ${CMAKE_STATIC_LIBRARY_PREFIX}curl${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}curl${CMAKE_STATIC_LIBRARY_SUFFIX}
               curl
            )
         endif()
      endif()
      message( STATUS "CURL_LIBRARY is ${CURL_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( CURL_LIBRARY)
         #
         # Add CURL_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark curl no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${CURL_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark curl no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_CURL_ROOT "${CURL_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_CURL_ROOT "${_TMP_CURL_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark curl no-cmake-dependency`
         #
         foreach( _TMP_CURL_NAME "curl" "curl-d")
            set( _TMP_CURL_DIR "${_TMP_CURL_ROOT}/include/${_TMP_CURL_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_CURL_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_CURL_DIR}")
               # we only want top level INHERIT_OBJC_LOADERS, so disable them
               if( NOT NO_INHERIT_OBJC_LOADERS)
                  set( NO_INHERIT_OBJC_LOADERS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_LOADERS ${NO_INHERIT_OBJC_LOADERS})
               set( NO_INHERIT_OBJC_LOADERS ON)
               #
               include( "${_TMP_CURL_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_LOADERS -1 NO_INHERIT_OBJC_LOADERS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_LOADERS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_CURL_DIR}")
               #
               unset( CURL_DEFINITIONS)
               include( "${_TMP_CURL_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${CURL_DEFINITIONS})
               break()
            else()
               message( STATUS "${_TMP_CURL_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark curl no-require-link`
         message( SEND_ERROR "CURL_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}curl-d${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}curl-d${CMAKE_STATIC_LIBRARY_SUFFIX}
curl-d")
      endif()
   endif()
endif()


#
# Generated from sourcetree: 7471542C-7E1A-4714-86BC-9ED490614DF9;MulleFoundationBase;no-singlephase;
# Disable with : `mulle-sourcetree mark MulleFoundationBase no-link`
# Disable for this platform: `mulle-sourcetree mark MulleFoundationBase no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleFoundationBase no-cmake-sdk-<name>`
#
if( COLLECT_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES "MulleFoundationBase")
else()
   if( NOT MULLE_FOUNDATION_BASE_LIBRARY)
      find_library( MULLE_FOUNDATION_BASE_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}MulleFoundationBase${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}MulleFoundationBase${CMAKE_STATIC_LIBRARY_SUFFIX}
         MulleFoundationBase
         NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
      )
      if( NOT MULLE_FOUNDATION_BASE_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
         find_library( MULLE_FOUNDATION_BASE_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}MulleFoundationBase${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}MulleFoundationBase${CMAKE_STATIC_LIBRARY_SUFFIX}
            MulleFoundationBase
         )
      endif()
      message( STATUS "MULLE_FOUNDATION_BASE_LIBRARY is ${MULLE_FOUNDATION_BASE_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE_FOUNDATION_BASE_LIBRARY)
         #
         # Add MULLE_FOUNDATION_BASE_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark MulleFoundationBase no-cmake-add`
         #
         list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE_FOUNDATION_BASE_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark MulleFoundationBase no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE_FOUNDATION_BASE_ROOT "${MULLE_FOUNDATION_BASE_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE_FOUNDATION_BASE_ROOT "${_TMP_MULLE_FOUNDATION_BASE_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark MulleFoundationBase no-cmake-dependency`
         #
         foreach( _TMP_MULLE_FOUNDATION_BASE_NAME "MulleFoundationBase")
            set( _TMP_MULLE_FOUNDATION_BASE_DIR "${_TMP_MULLE_FOUNDATION_BASE_ROOT}/include/${_TMP_MULLE_FOUNDATION_BASE_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE_FOUNDATION_BASE_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_FOUNDATION_BASE_DIR}")
               #
               include( "${_TMP_MULLE_FOUNDATION_BASE_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_FOUNDATION_BASE_DIR}")
               #
               unset( MULLE_FOUNDATION_BASE_DEFINITIONS)
               include( "${_TMP_MULLE_FOUNDATION_BASE_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE_FOUNDATION_BASE_DEFINITIONS})
               break()
            else()
               message( STATUS "${_TMP_MULLE_FOUNDATION_BASE_DIR} not found")
            endif()
         endforeach()
         #
         # Search for "MulleObjCLoader+<name>.h" in include directory.
         # Disable with: `mulle-sourcetree mark MulleFoundationBase no-cmake-loader`
         #
         if( NOT NO_INHERIT_OBJC_LOADERS)
            foreach( _TMP_MULLE_FOUNDATION_BASE_NAME "MulleFoundationBase")
               set( _TMP_MULLE_FOUNDATION_BASE_FILE "${_TMP_MULLE_FOUNDATION_BASE_ROOT}/include/${_TMP_MULLE_FOUNDATION_BASE_NAME}/MulleObjCLoader+${_TMP_MULLE_FOUNDATION_BASE_NAME}.h")
               if( EXISTS "${_TMP_MULLE_FOUNDATION_BASE_FILE}")
                  list( APPEND INHERITED_OBJC_LOADERS ${_TMP_MULLE_FOUNDATION_BASE_FILE})
                  break()
               endif()
            endforeach()
         endif()
      else()
         # Disable with: `mulle-sourcetree mark MulleFoundationBase no-require-link`
         message( SEND_ERROR "MULLE_FOUNDATION_BASE_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}MulleFoundationBase${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}MulleFoundationBase${CMAKE_STATIC_LIBRARY_SUFFIX}
MulleFoundationBase")
      endif()
   endif()
endif()


#
# Generated from sourcetree: f3c54219-3d56-4d37-8e04-2aed97ace766;MulleZlib;no-singlephase;
# Disable with : `mulle-sourcetree mark MulleZlib no-link`
# Disable for this platform: `mulle-sourcetree mark MulleZlib no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark MulleZlib no-cmake-sdk-<name>`
#
if( COLLECT_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES "MulleZlib")
else()
   if( NOT MULLE_ZLIB_LIBRARY)
      find_library( MULLE_ZLIB_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}MulleZlib${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}MulleZlib${CMAKE_STATIC_LIBRARY_SUFFIX}
         MulleZlib
         NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
      )
      if( NOT MULLE_ZLIB_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
         find_library( MULLE_ZLIB_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}MulleZlib${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}MulleZlib${CMAKE_STATIC_LIBRARY_SUFFIX}
            MulleZlib
         )
      endif()
      message( STATUS "MULLE_ZLIB_LIBRARY is ${MULLE_ZLIB_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE_ZLIB_LIBRARY)
         #
         # Add MULLE_ZLIB_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark MulleZlib no-cmake-add`
         #
         list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE_ZLIB_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark MulleZlib no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE_ZLIB_ROOT "${MULLE_ZLIB_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE_ZLIB_ROOT "${_TMP_MULLE_ZLIB_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark MulleZlib no-cmake-dependency`
         #
         foreach( _TMP_MULLE_ZLIB_NAME "MulleZlib")
            set( _TMP_MULLE_ZLIB_DIR "${_TMP_MULLE_ZLIB_ROOT}/include/${_TMP_MULLE_ZLIB_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE_ZLIB_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE_ZLIB_DIR}")
               #
               include( "${_TMP_MULLE_ZLIB_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE_ZLIB_DIR}")
               #
               unset( MULLE_ZLIB_DEFINITIONS)
               include( "${_TMP_MULLE_ZLIB_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE_ZLIB_DEFINITIONS})
               break()
            else()
               message( STATUS "${_TMP_MULLE_ZLIB_DIR} not found")
            endif()
         endforeach()
         #
         # Search for "MulleObjCLoader+<name>.h" in include directory.
         # Disable with: `mulle-sourcetree mark MulleZlib no-cmake-loader`
         #
         if( NOT NO_INHERIT_OBJC_LOADERS)
            foreach( _TMP_MULLE_ZLIB_NAME "MulleZlib")
               set( _TMP_MULLE_ZLIB_FILE "${_TMP_MULLE_ZLIB_ROOT}/include/${_TMP_MULLE_ZLIB_NAME}/MulleObjCLoader+${_TMP_MULLE_ZLIB_NAME}.h")
               if( EXISTS "${_TMP_MULLE_ZLIB_FILE}")
                  list( APPEND INHERITED_OBJC_LOADERS ${_TMP_MULLE_ZLIB_FILE})
                  break()
               endif()
            endforeach()
         endif()
      else()
         # Disable with: `mulle-sourcetree mark MulleZlib no-require-link`
         message( SEND_ERROR "MULLE_ZLIB_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}MulleZlib${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}MulleZlib${CMAKE_STATIC_LIBRARY_SUFFIX}
MulleZlib")
      endif()
   endif()
endif()
