/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_FOUNDATION_BASE_VERSION)
# if MULLE_FOUNDATION_BASE_VERSION < ((0 << 20) | (22 << 8) | 0)
#  error "MulleFoundationBase is too old"
# endif
# if MULLE_FOUNDATION_BASE_VERSION >= ((0 << 20) | (23 << 8) | 0)
#  error "MulleFoundationBase is too new"
# endif
#endif

#if defined( MULLE_ZLIB_VERSION)
# if MULLE_ZLIB_VERSION < ((0 << 20) | (15 << 8) | 9)
#  error "MulleZlib is too old"
# endif
# if MULLE_ZLIB_VERSION >= ((0 << 20) | (16 << 8) | 0)
#  error "MulleZlib is too new"
# endif
#endif
