/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_curl_include_h__
#define _mulle_curl_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove ssl`
// (Use EE48C273-5D2B-49DC-ADC6-627F85AA4C59 instead of ssl, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark ssl no-header`
//    rename              : `mulle-sde dependency|library set ssl include whatever.h`
//    reorder             : `mulle-sde dependency move ssl <up|down>`
//    toggle #include: `mulle-sde dependency mark ssl [no-]import`
//    toggle public       : `mulle-sde dependency mark ssl [no-]public`
//    toggle optional     : `mulle-sde dependency mark ssl [no-]require`
//    remove for platform : `mulle-sde dependency mark ssl no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <openssl/ssl.h>   // ssl

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove curl`
// (Use 78cfb19c-00ec-4df6-9c13-00a6aa134000 instead of curl, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark curl no-header`
//    rename              : `mulle-sde dependency|library set curl include whatever.h`
//    reorder             : `mulle-sde dependency move curl <up|down>`
//    toggle #include: `mulle-sde dependency mark curl [no-]import`
//    toggle public       : `mulle-sde dependency mark curl [no-]public`
//    toggle optional     : `mulle-sde dependency mark curl [no-]require`
//    remove for platform : `mulle-sde dependency mark curl no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <curl/curl.h>   // curl

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove CoreFoundation`
// (Use A56B487A-7396-4D4B-AA7B-623F374684FA instead of CoreFoundation, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark CoreFoundation no-header`
//    rename              : `mulle-sde dependency|library set CoreFoundation include whatever.h`
//    reorder             : `mulle-sde dependency move CoreFoundation <up|down>`
//    toggle #include: `mulle-sde dependency mark CoreFoundation [no-]import`
//    toggle public       : `mulle-sde dependency mark CoreFoundation [no-]public`
//    toggle optional     : `mulle-sde dependency mark CoreFoundation [no-]require`
//    remove for platform : `mulle-sde dependency mark CoreFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if defined( __APPLE__)
# include <CoreFoundation/CoreFoundation.h>   // CoreFoundation
#endif

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove SystemConfiguration`
// (Use B3B65A22-31FC-43CE-AF35-46BC30A3AE01 instead of SystemConfiguration, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark SystemConfiguration no-header`
//    rename              : `mulle-sde dependency|library set SystemConfiguration include whatever.h`
//    reorder             : `mulle-sde dependency move SystemConfiguration <up|down>`
//    toggle #include: `mulle-sde dependency mark SystemConfiguration [no-]import`
//    toggle public       : `mulle-sde dependency mark SystemConfiguration [no-]public`
//    toggle optional     : `mulle-sde dependency mark SystemConfiguration [no-]require`
//    remove for platform : `mulle-sde dependency mark SystemConfiguration no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
# if defined( __APPLE__)
# include <SystemConfiguration/SystemConfiguration.h>   // SystemConfiguration
#endif

#endif
