/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleCurl_include_h__
#define _MulleCurl_include_h__

// How to tweak the following curl #include
//    remove:             `mulle-sourcetree mark curl no-header`
//    rename:             `mulle-sde dependency|library set curl include whatever.h`
//    toggle #import:     `mulle-sourcetree mark curl [no-]import`
//    toggle localheader: `mulle-sourcetree mark curl [no-]localheader`
//    toggle public:      `mulle-sourcetree mark curl [no-]public`
//    toggle optional:    `mulle-sourcetree mark curl [no-]require`
//    remove for os:      `mulle-sourcetree mark curl no-os-<osname>`
# if defined( __has_include) && __has_include("curl.h")
#   include "curl.h"   // curl
# else
#   include <curl/curl.h>   // curl
# endif

// How to tweak the following ssl #include
//    remove:             `mulle-sourcetree mark ssl no-header`
//    rename:             `mulle-sde dependency|library set ssl include whatever.h`
//    toggle #import:     `mulle-sourcetree mark ssl [no-]import`
//    toggle localheader: `mulle-sourcetree mark ssl [no-]localheader`
//    toggle public:      `mulle-sourcetree mark ssl [no-]public`
//    toggle optional:    `mulle-sourcetree mark ssl [no-]require`
//    remove for os:      `mulle-sourcetree mark ssl no-os-<osname>`
# if defined( __has_include) && __has_include("ssl.h")
#   include "ssl.h"   // ssl
# else
#   include <openssl/ssl.h>   // ssl
# endif

#endif
