/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_curl_include_h__
#define _mulle_curl_include_h__

// You can tweak the following #include with these commands.
// (Use EE48C273-5D2B-49DC-ADC6-627F85AA4C59 instead of ssl if there are duplicate entries)
//    remove:             `mulle-sourcetree mark ssl no-header`
//    rename:             `mulle-sde dependency|library set ssl include whatever.h`
//    reorder:            `mulle-sourcetree move ssl <up|down>`
//    toggle #include:    `mulle-sourcetree mark ssl [no-]import`
//    toggle public:      `mulle-sourcetree mark ssl [no-]public`
//    toggle optional:    `mulle-sourcetree mark ssl [no-]require`
//    remove for platform:`mulle-sourcetree mark ssl no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <openssl/ssl.h>   // ssl

// You can tweak the following #include with these commands.
// (Use 78cfb19c-00ec-4df6-9c13-00a6aa134000 instead of curl if there are duplicate entries)
//    remove:             `mulle-sourcetree mark curl no-header`
//    rename:             `mulle-sde dependency|library set curl include whatever.h`
//    reorder:            `mulle-sourcetree move curl <up|down>`
//    toggle #include:    `mulle-sourcetree mark curl [no-]import`
//    toggle public:      `mulle-sourcetree mark curl [no-]public`
//    toggle optional:    `mulle-sourcetree mark curl [no-]require`
//    remove for platform:`mulle-sourcetree mark curl no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <curl/curl.h>   // curl

#endif
