      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( MulleCurl), @selector( ClassMethods) },      // 9714448a;MulleCurl;3ab759f1;ClassMethods
      { @selector( MulleCurl), MULLE_OBJC_NO_CATEGORYID },      // 9714448a;MulleCurl;;
      { @selector( NSMutableData), @selector( MulleCurlParser) },      // 5d7fdc81;NSMutableData;3ef706fe;MulleCurlParser
