      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleObjCCurl), MULLE_OBJC_NO_CATEGORYID },      // 7f36a4a4;MulleObjCCurl;;
      { @selector( MulleObjCHTTPHeaderParser), @selector( MulleObjCCurlParser) },      // 1f2810ad;MulleObjCHTTPHeaderParser;cea2d1dd;MulleObjCCurlParser
      { @selector( MulleObjCHTTPHeaderParser), MULLE_OBJC_NO_CATEGORYID },      // 1f2810ad;MulleObjCHTTPHeaderParser;;
      { @selector( NSMutableData), @selector( MulleObjCCurlParser) },      // 5d7fdc81;NSMutableData;cea2d1dd;MulleObjCCurlParser
