      { @selector( MulleObjCLoader), @selector( MulleObjCInetFoundation) },      // 47a9beb6;MulleObjCLoader;088ec1b3;MulleObjCInetFoundation
      { @selector( MulleCurl), @selector( ClassMethods) },      // 9714448a;MulleCurl;3ab759f1;ClassMethods
      { @selector( MulleCurl), MULLE_OBJC_NO_CATEGORYID },      // 9714448a;MulleCurl;;
      { @selector( MulleHTTPHeaderParser), @selector( MulleCurlParser) },      // 33ba7405;MulleHTTPHeaderParser;3ef706fe;MulleCurlParser
      { @selector( MulleHTTPHeaderParser), MULLE_OBJC_NO_CATEGORYID },      // 33ba7405;MulleHTTPHeaderParser;;
      { @selector( NSMutableData), @selector( MulleCurlParser) },      // 5d7fdc81;NSMutableData;3ef706fe;MulleCurlParser
