#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
)

set( PRIVATE_HEADERS
src/MulleObjCCurl+Private.h
src/import-private.h
)

set( PUBLIC_HEADERS
src/MulleObjCCurlFoundation.h
src/MulleObjCCurlParser.h
src/MulleObjCCurl.h
src/MulleObjCHTTPHeaderParser.h
src/MulleObjCLoader+MulleObjCCurlFoundation.h
src/import.h
)

