#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleCurl+ClassMethods.m
src/MulleCurl+Private.m
src/MulleCurl.m
src/NSMutableData+MulleCurlParser.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleCurl.m
)
