#
# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( SOURCES
src/MulleObjCCurlFoundation.m
src/MulleObjCCurlFoundation-shlib.m
src/MulleObjCCurl+Private.m
src/MulleObjCCurl.m
src/MulleObjCHTTPHeaderParser.m
)

set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCCurlFoundation.m
)
